-- Campos administrativos usados por el modulo de clustering.
-- Script idempotente para PostgreSQL.

BEGIN;

ALTER TABLE operativo.studies
  ADD COLUMN IF NOT EXISTS "sampleType" varchar(50) NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS "requiresSpecialProcessing" boolean DEFAULT NULL;

CREATE TABLE IF NOT EXISTS operativo.study_request_metrics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  study_id integer NOT NULL,
  period_month date NOT NULL,
  request_count integer NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  is_synthetic boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_study_request_metrics_study
    FOREIGN KEY (study_id) REFERENCES operativo.studies(id) ON DELETE CASCADE,
  CONSTRAINT uq_study_request_metrics_period
    UNIQUE (study_id, period_month)
);

CREATE INDEX IF NOT EXISTS idx_study_request_metrics_study
  ON operativo.study_request_metrics(study_id);

CREATE INDEX IF NOT EXISTS idx_study_request_metrics_period
  ON operativo.study_request_metrics(period_month);

CREATE INDEX IF NOT EXISTS idx_study_details_clustering
  ON operativo.study_details(study_id)
  WHERE "dataType" = 'parameter' AND "isActive" = true;

CREATE INDEX IF NOT EXISTS idx_service_order_items_study
  ON operativo.service_order_items(study_id);

CREATE INDEX IF NOT EXISTS idx_service_order_items_order
  ON operativo.service_order_items(service_order_id);

-- Cada recalculo queda almacenado como una fotografia inmutable del modelo.
CREATE TABLE IF NOT EXISTS operativo.study_clustering_runs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  executed_at timestamp with time zone NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'running',
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  period_months integer NOT NULL CHECK (period_months BETWEEN 1 AND 24),
  include_synthetic boolean NOT NULL DEFAULT false,
  requested_k integer,
  max_k integer NOT NULL CHECK (max_k BETWEEN 2 AND 6),
  selected_k integer CHECK (selected_k BETWEEN 2 AND 6),
  elbow_k integer CHECK (elbow_k BETWEEN 2 AND 6),
  selection_method varchar(50),
  silhouette_score double precision,
  inertia double precision,
  total_studies integer NOT NULL CHECK (total_studies >= 0),
  profile_count integer NOT NULL CHECK (profile_count >= 0),
  outlier_count integer NOT NULL CHECK (outlier_count >= 0),
  algorithm varchar(50) NOT NULL DEFAULT 'kmeans',
  model_version varchar(30) NOT NULL,
  evaluations jsonb NOT NULL DEFAULT '[]'::jsonb,
  feature_names jsonb NOT NULL DEFAULT '[]'::jsonb,
  excluded_features jsonb NOT NULL DEFAULT '[]'::jsonb,
  data_quality jsonb NOT NULL DEFAULT '{}'::jsonb,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  sources jsonb NOT NULL DEFAULT '{}'::jsonb,
  interpretation_thresholds jsonb NOT NULL DEFAULT '{}'::jsonb,
  findings jsonb NOT NULL DEFAULT '[]'::jsonb,
  failure_message text,
  created_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_study_clustering_run_status
    CHECK (status IN ('running', 'completed', 'failed')),
  CONSTRAINT ck_study_clustering_run_period
    CHECK (period_end >= period_start)
);

CREATE INDEX IF NOT EXISTS idx_study_clustering_runs_executed_at
  ON operativo.study_clustering_runs(executed_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_study_clustering_runs_status_latest
  ON operativo.study_clustering_runs(status, executed_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS operativo.study_clustering_profiles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id integer NOT NULL,
  cluster_number integer NOT NULL CHECK (cluster_number >= 1),
  suggested_name varchar(150) NOT NULL,
  display_name varchar(150) NOT NULL,
  display_name_key varchar(150) NOT NULL,
  short_description text NOT NULL,
  key_characteristics jsonb NOT NULL DEFAULT '[]'::jsonb,
  study_count integer NOT NULL CHECK (study_count >= 0),
  percentage double precision NOT NULL,
  averages jsonb NOT NULL DEFAULT '{}'::jsonb,
  predominant_method varchar(150),
  predominant_sample_type varchar(100),
  special_processing_percentage double precision NOT NULL,
  outlier_count integer NOT NULL CHECK (outlier_count >= 0),
  outlier_threshold double precision,
  technical_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_study_clustering_profiles_run
    FOREIGN KEY (run_id)
    REFERENCES operativo.study_clustering_runs(id)
    ON DELETE CASCADE,
  CONSTRAINT uq_study_clustering_profiles_run_cluster
    UNIQUE (run_id, cluster_number),
  CONSTRAINT uq_study_clustering_profiles_run_display_name
    UNIQUE (run_id, display_name_key)
);

CREATE INDEX IF NOT EXISTS idx_study_clustering_profiles_run
  ON operativo.study_clustering_profiles(run_id);

CREATE TABLE IF NOT EXISTS operativo.study_clustering_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id integer NOT NULL,
  profile_id integer NOT NULL,
  study_id integer NOT NULL,
  study_code_snapshot varchar(50) NOT NULL,
  study_name_snapshot varchar(200) NOT NULL,
  distance_to_centroid double precision NOT NULL,
  outlier_score double precision NOT NULL,
  is_outlier boolean NOT NULL DEFAULT false,
  is_synthetic boolean NOT NULL DEFAULT false,
  values jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_study_clustering_assignments_run
    FOREIGN KEY (run_id)
    REFERENCES operativo.study_clustering_runs(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_study_clustering_assignments_profile
    FOREIGN KEY (profile_id)
    REFERENCES operativo.study_clustering_profiles(id)
    ON DELETE CASCADE,
  CONSTRAINT uq_study_clustering_assignments_run_study
    UNIQUE (run_id, study_id)
);

CREATE INDEX IF NOT EXISTS idx_study_clustering_assignments_run
  ON operativo.study_clustering_assignments(run_id);

CREATE INDEX IF NOT EXISTS idx_study_clustering_assignments_profile
  ON operativo.study_clustering_assignments(profile_id);

COMMIT;
