-- Campos administrativos usados por el modulo de clustering.
-- Script idempotente para PostgreSQL.

BEGIN;

ALTER TABLE operativo.studies
  ADD COLUMN IF NOT EXISTS "sampleType" varchar(50) NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS "requiresSpecialProcessing" boolean DEFAULT NULL;

CREATE TABLE IF NOT EXISTS operativo.study_request_metrics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  study_id integer NOT NULL,
  period_month date NOT NULL,
  request_count integer NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  is_synthetic boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_study_request_metrics_study
    FOREIGN KEY (study_id) REFERENCES operativo.studies(id) ON DELETE CASCADE,
  CONSTRAINT uq_study_request_metrics_period
    UNIQUE (study_id, period_month)
);

CREATE INDEX IF NOT EXISTS idx_study_request_metrics_study
  ON operativo.study_request_metrics(study_id);

CREATE INDEX IF NOT EXISTS idx_study_request_metrics_period
  ON operativo.study_request_metrics(period_month);

CREATE INDEX IF NOT EXISTS idx_study_details_clustering
  ON operativo.study_details(study_id)
  WHERE "dataType" = 'parameter' AND "isActive" = true;

CREATE INDEX IF NOT EXISTS idx_service_order_items_study
  ON operativo.service_order_items(study_id);

CREATE INDEX IF NOT EXISTS idx_service_order_items_order
  ON operativo.service_order_items(service_order_id);

COMMIT;
