-- ================================================================
-- ECONOLAB: dataset sintetico para el modelo de precio
-- PostgreSQL
--
-- Crea 1,000 estudios de entrenamiento y sus parametros.
-- Es idempotente: puede ejecutarse nuevamente sin duplicar registros.
-- Los registros quedan suspendidos y ocultos del catalogo operativo.
-- ================================================================

BEGIN;

-- El mismo dataset tambien puede utilizarse en el modo academico del clustering.
ALTER TABLE operativo.studies
  ADD COLUMN IF NOT EXISTS "sampleType" varchar(50) NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS "requiresSpecialProcessing" boolean DEFAULT NULL;

CREATE TABLE IF NOT EXISTS operativo.study_request_metrics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  study_id integer NOT NULL REFERENCES operativo.studies(id) ON DELETE CASCADE,
  period_month date NOT NULL,
  request_count integer NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  is_synthetic boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_study_request_metrics_period UNIQUE (study_id, period_month)
);

WITH base AS (
  SELECT
    series_number,
    1 + ((series_number * 7) % 30) AS parameter_count,
    (ARRAY[
      'blood',
      'serum',
      'plasma',
      'urine',
      'stool',
      'swab',
      'other'
    ])[1 + ((series_number * 3) % 7)] AS sample_type,
    (ARRAY[
      'ENZIMATICO',
      'INMUNOENSAYO',
      'ESPECTROFOTOMETRIA',
      'COLORIMETRIA',
      'COAGULOMETRIA',
      'ELISA',
      'QUIMIOLUMINISCENCIA',
      'PCR'
    ])[1 + ((series_number - 1) % 8)] AS method
  FROM generate_series(1, 1000) AS series_number
),
features AS (
  SELECT
    *,
    CASE method
      WHEN 'ENZIMATICO' THEN 40
      WHEN 'INMUNOENSAYO' THEN 120
      WHEN 'ESPECTROFOTOMETRIA' THEN 70
      WHEN 'COLORIMETRIA' THEN 50
      WHEN 'COAGULOMETRIA' THEN 90
      WHEN 'ELISA' THEN 150
      WHEN 'QUIMIOLUMINISCENCIA' THEN 180
      WHEN 'PCR' THEN 350
    END AS price_method_effect,
    CASE method
      WHEN 'ENZIMATICO' THEN 15
      WHEN 'INMUNOENSAYO' THEN 60
      WHEN 'ESPECTROFOTOMETRIA' THEN 30
      WHEN 'COLORIMETRIA' THEN 20
      WHEN 'COAGULOMETRIA' THEN 45
      WHEN 'ELISA' THEN 90
      WHEN 'QUIMIOLUMINISCENCIA' THEN 120
      WHEN 'PCR' THEN 360
    END AS duration_method_effect
  FROM base
),
training_rows AS (
  SELECT
    *,
    GREATEST(
      50,
      ROUND((
        70
        + parameter_count * 22
        + price_method_effect
        + ((series_number * 37) % 51 - 25)
      ) / 10.0) * 10
    )::numeric(10, 2) AS normal_price,
    GREATEST(
      15,
      ROUND((
        15
        + parameter_count * 4
        + duration_method_effect
        + ((series_number * 13) % 21 - 10)
      ) / 15.0) * 15
    )::integer AS duration_minutes,
    (
      method IN ('PCR', 'QUIMIOLUMINISCENCIA')
      OR parameter_count >= 25
    ) AS requires_special_processing
  FROM features
)
INSERT INTO operativo.studies (
  name,
  code,
  description,
  "durationMinutes",
  "normalPrice",
  "difPrice",
  "specialPrice",
  "hospitalPrice",
  "otherPrice",
  "defaultDiscountPercent",
  method,
  "sampleType",
  "requiresSpecialProcessing",
  indicator,
  "isActive",
  type,
  status,
  "packageStudyIds"
)
SELECT
  'ESTUDIO SINTETICO ML ' || LPAD(series_number::text, 6, '0'),
  'MLTRAIN-' || LPAD(series_number::text, 6, '0'),
  'Registro sintetico para entrenar el modelo. No usar en operacion.',
  -- Es una variable operativa del clustering; la regresion no la predice.
  duration_minutes,
  normal_price,
  ROUND(normal_price * 0.80, 2),
  ROUND(normal_price * 0.90, 2),
  ROUND(normal_price * 1.15, 2),
  ROUND(normal_price * 1.20, 2),
  0,
  method,
  sample_type,
  requires_special_processing,
  'DATOS SINTETICOS',
  false,
  'study'::operativo.studies_type_enum,
  'suspended'::operativo.studies_status_enum,
  ARRAY[]::integer[]
FROM training_rows
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  "durationMinutes" = EXCLUDED."durationMinutes",
  "normalPrice" = EXCLUDED."normalPrice",
  "difPrice" = EXCLUDED."difPrice",
  "specialPrice" = EXCLUDED."specialPrice",
  "hospitalPrice" = EXCLUDED."hospitalPrice",
  "otherPrice" = EXCLUDED."otherPrice",
  "defaultDiscountPercent" = EXCLUDED."defaultDiscountPercent",
  method = EXCLUDED.method,
  "sampleType" = EXCLUDED."sampleType",
  "requiresSpecialProcessing" = EXCLUDED."requiresSpecialProcessing",
  indicator = EXCLUDED.indicator,
  "isActive" = EXCLUDED."isActive",
  type = EXCLUDED.type,
  status = EXCLUDED.status,
  "packageStudyIds" = EXCLUDED."packageStudyIds",
  "updatedAt" = NOW();

-- Demanda mensual sintetica para los ultimos 24 meses, incluido el actual.
WITH synthetic_studies AS (
  SELECT id, REPLACE(code, 'MLTRAIN-', '')::integer AS series_number
  FROM operativo.studies
  WHERE code ~ '^MLTRAIN-[0-9]{6}$'
    AND indicator = 'DATOS SINTETICOS'
),
months AS (
  SELECT generate_series(
    (date_trunc('month', CURRENT_DATE) - INTERVAL '23 months')::date,
    date_trunc('month', CURRENT_DATE)::date,
    INTERVAL '1 month'
  )::date AS period_month
)
INSERT INTO operativo.study_request_metrics (
  study_id,
  period_month,
  request_count,
  is_synthetic
)
SELECT
  study.id,
  month.period_month,
  1 + ((study.series_number * 29 + EXTRACT(MONTH FROM month.period_month)::integer * 11) % 45),
  true
FROM synthetic_studies AS study
CROSS JOIN months AS month
ON CONFLICT (study_id, period_month) DO UPDATE SET
  request_count = EXCLUDED.request_count,
  is_synthetic = true,
  updated_at = NOW();

-- Cada estudio recibe entre 1 y 30 parametros.
WITH synthetic_studies AS (
  SELECT
    id,
    1 + ((REPLACE(code, 'MLTRAIN-', '')::integer * 7) % 30) AS parameter_count
  FROM operativo.studies
  WHERE code ~ '^MLTRAIN-[0-9]{6}$'
    AND indicator = 'DATOS SINTETICOS'
)
INSERT INTO operativo.study_details (
  study_id,
  parent_id,
  "dataType",
  name,
  "sortOrder",
  unit,
  "referenceValue",
  "isActive"
)
SELECT
  study.id,
  NULL,
  'parameter'::operativo.study_details_datatype_enum,
  'ML PARAMETRO ' || LPAD(parameter_number::text, 3, '0'),
  parameter_number,
  'unidad',
  'Rango de referencia sintetico',
  true
FROM synthetic_studies AS study
CROSS JOIN LATERAL generate_series(1, study.parameter_count) AS parameter_number
WHERE NOT EXISTS (
  SELECT 1
  FROM operativo.study_details AS detail
  WHERE detail.study_id = study.id
    AND detail."dataType" = 'parameter'::operativo.study_details_datatype_enum
    AND detail."sortOrder" = parameter_number
    AND detail.name LIKE 'ML PARAMETRO %'
);

COMMIT;

-- ================================================================
-- VERIFICACION: debe devolver 1,000 estudios.
-- ================================================================

SELECT
  COUNT(*) AS synthetic_studies,
  MIN("normalPrice") AS minimum_price,
  ROUND(AVG("normalPrice"), 2) AS average_price,
  MAX("normalPrice") AS maximum_price
FROM operativo.studies
WHERE code ~ '^MLTRAIN-[0-9]{6}$'
  AND indicator = 'DATOS SINTETICOS';

SELECT COUNT(*) AS synthetic_parameters
FROM operativo.study_details AS detail
INNER JOIN operativo.studies AS study ON study.id = detail.study_id
WHERE study.code ~ '^MLTRAIN-[0-9]{6}$'
  AND study.indicator = 'DATOS SINTETICOS';

SELECT COUNT(*) AS synthetic_demand_rows
FROM operativo.study_request_metrics AS metric
INNER JOIN operativo.studies AS study ON study.id = metric.study_id
WHERE study.code ~ '^MLTRAIN-[0-9]{6}$'
  AND study.indicator = 'DATOS SINTETICOS'
  AND metric.is_synthetic = true;

-- ================================================================
-- ROLLBACK MANUAL (ejecutar solo si se desea retirar el dataset).
-- Las lineas estan comentadas para evitar borrados accidentales.
-- ================================================================

-- BEGIN;
-- DELETE FROM operativo.study_request_metrics
-- WHERE study_id IN (
--   SELECT id FROM operativo.studies
--   WHERE code ~ '^MLTRAIN-[0-9]{6}$'
--     AND indicator = 'DATOS SINTETICOS'
-- );
-- DELETE FROM operativo.study_details
-- WHERE study_id IN (
--   SELECT id
--   FROM operativo.studies
--   WHERE code ~ '^MLTRAIN-[0-9]{6}$'
--     AND indicator = 'DATOS SINTETICOS'
-- );
-- DELETE FROM operativo.studies
-- WHERE code ~ '^MLTRAIN-[0-9]{6}$'
--   AND indicator = 'DATOS SINTETICOS';
-- COMMIT;
